spring.application.name=app
server.port=7070

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

spring.datasource.url=jdbc:postgresql://localhost:5432/task-manager
spring.datasource.username=postgres
spring.datasource.password=5753

rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem